---
# Restart nginx is actually not working, start and stop work but not restart
- name: restart nginx
  service: name=nginx state=restarted sleep=2
  sudo_user: root

- name: reload nginx
  service: name=nginx state=reloaded
  sudo_user: root

- name: restart web frontend
  action: service name=${project_name}_gunicorn state=restarted
  sudo_user: root

- name: restart uwsgi
  service: name=uwsgi state=restarted 
  sudo_user: root

