---
# Play to configure instances
- name: Configure webservers
  hosts: webservers
  user: ubuntu
  gather_facts: false
  sudo: true
  

  #Include configuration information
  vars_files:
    # The envirnoment variables have been setup up at run time via eg --extra-vars "@vars/development.yml"
    - vars/base.yml # Standard setup for all environments which will overwrite and extra vars
    - ../../personal.yml #Defines database PW, GIT tokens etc, information specific to me
    #Further information will come from ../../galleria_private/development/development but into Django settings

  roles:
     - common
     - webservers
 

