---
# Play to configure instances
- name: Configure webservers
  hosts: webservers
  user: ubuntu
  gather_facts: false
  sudo: true
  

  #Include secret information outside of git a copy of a template is in the files
  #directory
  vars_files:
    - vars/base.yml # Standard setup for all environments
    # assumes setup for environment is done at run time by
    - ../../personal.yml #Defines database PW

  roles:
     - common
     - webservers
 

