---
# Play to make this machine a document provider
- name: Configure webservers
  hosts: local
  user: trusty
  connection: local
  gather_facts: false
  
  vars_files:
    - vars.yml

  roles:
     - docs
 

