---
# Playbook to deploy to the local machine
- name: deploy locally
  hosts: local
  user: trusty
  connection: local
  gather_facts: false

  vars_files:
    - vars/base.yml # Standard setup for all environments
    # assumes setup for environment is done at run time by
    - ../../personal.yml #Defines database PW

  roles:
     - devmachine
     - postgres
 



